# Generated by Django 4.1.6 on 2023-02-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genero", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
            ],
            options={
                "ordering": ("-genero",),
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-fecha_publicacion",)},
        ),
    ]
