# Generated by Django 4.1.6 on 2023-02-04 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_posts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="posts",
        ),
        migrations.AddField(
            model_name="post",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blog.categoria",
            ),
        ),
    ]
