# Generated by Django 4.1.6 on 2023-02-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_post_posts_post_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="repositorio/"),
        ),
    ]
