# Generated by Django 4.1.6 on 2023-02-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=256)),
                ("apellido", models.CharField(max_length=256)),
                ("dni", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254)),
                ("fecha_nacimiento", models.DateField(null=True)),
            ],
        ),
    ]
