# Generated by Django 4.1.6 on 2023-02-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_fecha_publicacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categoria",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
